package com.algonquin.www.model;
/**
 * Request model for user registration.
 * <p>
 * Contains user details required for registration including ID, username,
 * password, email, name, and user type.
 * </p>
 */

public class RegisterRequest {
    private String id;
    private String username;
    private String password;
    private String email;
    private String name;
    private String type;
    
    /**
     * Gets the user ID.
     * <p>
     * This field may be optional depending on whether IDs are generated by the system.
     * </p>
     *
     * @return the user ID
     */

    public String getId() {
        return id;
    }
     /**
     * Sets the user ID.
     *
     * @param id the user ID
     */

    public void setId(String id) {
        this.id = id;
    }
     /**
     * Gets the username for registration.
     *
     * @return the username
     */

    public String getUsername() {
        return username;
    }
     /**
     * Sets the username for registration.
     *
     * @param username the username
     */

    public void setUsername(String username) {
        this.username = username;
    }
    /**
     * Gets the password for registration.
     *
     * @return the password
     */

    public String getPassword() {
        return password;
    }
     /**
     * Sets the password for registration.
     *
     * @param password the password
     */

    public void setPassword(String password) {
        this.password = password;
    }
     /**
     * Gets the email address for registration.
     *
     * @return the email address
     */

    public String getEmail() {
        return email;
    }
    /**
     * Sets the email address for registration.
     *
     * @param email the email address
     */

    public void setEmail(String email) {
        this.email = email;
    }
        /**
     * Gets the full name of the user registering.
     *
     * @return the full name
     */


    public String getName() {
        return name;
    }
     /**
     * Sets the full name of the user registering.
     *
     * @param name the full name
     */

    public void setName(String name) {
        this.name = name;
    }
      /**
     * Gets the type of user.
     * <p>
     * Can represent roles such as admin, operator, or regular user.
     * </p>
     *
     * @return the user type
     */

    public String getType() {
        return type;
    }
     /**
     * Sets the type of user.
     *
     * @param type the user type
     */

    public void setType(String type) {
        this.type = type;
    }
}
